Qualtrics integration preliminary
Stanford-Health/wearipedia pull request #159
Opened 2024-05-14 22:32 UTC by cheejung

## Description

## Related Issue

2024-05-23 19:00 UTC, TrafficCop requested changes

2024-06-14 00:42 UTC, TrafficCop requested changes
Docstring format should match other devices

2024-08-19 07:29 UTC, TrafficCop requested changes

2024-08-19 07:29 UTC, TrafficCop commented on wearipedia/devices/qualtrics/qualtrics_gen.py
Since we need sample_survey.csv in the same directory, should that be added?

2024-09-30 00:01 UTC, cheejung commented on wearipedia/devices/qualtrics/patient_intake.csv
The patient_intake.csv should replace sample_survey.csv, which was just a placeholder. I'll change the generation code so that the new filename is reflected.

2024-09-30 00:07 UTC, cheejung commented on wearipedia/devices/qualtrics/qualtrics_gen.py
Done!

2025-01-06 23:18 UTC, TrafficCop reviewed
Quick question on synthetic data generator design.

2025-01-06 23:18 UTC, TrafficCop commented on wearipedia/devices/qualtrics/qualtrics_gen.py
I see, so we generate the survey the same way each time. Is this the desired behavior?

2025-01-07 17:45 UTC, TrafficCop approved these changes

2025-01-08 02:01 UTC, TrafficCop requested changes
1. Run make check-codestyle (few import style changes required)
2. Since you are adding some new packages here (qualtricsAPI), run "make install" and then commit the updated requirements.txt as well

2025-04-05 09:12 UTC, merged

2025-04-20 04:16 UTC, stefren commented on pyproject.toml
> +
This seems like a mistake in resolving the merge conflict here, as it's undone a number of changes I made on the main branch :(

2025-04-20 04:16 UTC, stefren commented on pyproject.toml
> +version = "0.1.2"
this also seems like a mistake